<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Belen Castro y Millaray Maulen">

<title>Uso de las redes sociales para informarse sobre política y su relacion con una actitud autoritaria</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="Uso de las redes sociales para informarse sobre política y su relación con una actitud autoritaria_files/libs/clipboard/clipboard.min.js"></script>
<script src="Uso de las redes sociales para informarse sobre política y su relación con una actitud autoritaria_files/libs/quarto-html/quarto.js"></script>
<script src="Uso de las redes sociales para informarse sobre política y su relación con una actitud autoritaria_files/libs/quarto-html/popper.min.js"></script>
<script src="Uso de las redes sociales para informarse sobre política y su relación con una actitud autoritaria_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Uso de las redes sociales para informarse sobre política y su relación con una actitud autoritaria_files/libs/quarto-html/anchor.min.js"></script>
<link href="Uso de las redes sociales para informarse sobre política y su relación con una actitud autoritaria_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Uso de las redes sociales para informarse sobre política y su relación con una actitud autoritaria_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Uso de las redes sociales para informarse sobre política y su relación con una actitud autoritaria_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Uso de las redes sociales para informarse sobre política y su relación con una actitud autoritaria_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Uso de las redes sociales para informarse sobre política y su relación con una actitud autoritaria_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Uso de las redes sociales para informarse sobre política y su relacion con una actitud autoritaria</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Belen Castro y Millaray Maulen </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introducción." class="level2">
<h2 class="anchored" data-anchor-id="introducción.">Introducción.</h2>
<p>En el Chile contemporáneo, la estabilidad, legitimidad y profundización del sistema democrático se han transformado en focos centrales del debate sociológico y político. Tras ciclos de alta movilización social, cuyo punto álgido se manifestó en el estallido social de 2019, y una serie de procesos constituyentes complejos, las bases sobre las cuales la ciudadanía evalúa a sus instituciones representativas han experimentado una profunda transformación. Este escenario está cruzado por una crisis de desafección y desconfianza generalizada, donde las promesas del orden democrático institucionalizado chocan con una ciudadanía cada vez más exigente, crítica y fragmentada.&nbsp;</p>
<p>Esto ha llevado a que actualmente han surgido en distintos lugares del mundo discursos los cuales pueden ser calificados como “populismos de extrema derecha” trayendo a la opinión pública y política ideas como “la exclusión del otro y la revaloración de una lógica del enfrentamiento entre amigos y enemigos, entre ellos y nosotros” <span class="citation" data-cites="barriaasenjo2022">(<a href="#ref-barriaasenjo2022" role="doc-biblioref">Barria Asenjo et al. 2022</a>)</span></p>
<p>Tal como plantea <span class="citation" data-cites="barriaasenjo2022">(<a href="#ref-barriaasenjo2022" role="doc-biblioref">Barria Asenjo et al. 2022</a>)</span> en su texto… este resurgimiento de un pensamiento autoritario y violento “se trata de una cuestión preocupante en la medida que en este escenario ideológico se pone en juego la validación de la violencia como medio de instalación de los objetivos políticos de ciertos colectivos” <span class="citation" data-cites="barriaasenjo2022">(<a href="#ref-barriaasenjo2022" role="doc-biblioref">Barria Asenjo et al. 2022</a>)</span></p>
<p>​En este entramado de desconfianza institucional y el surgimiento de discursos de extrema derecha y autoritarios la relación entre los ciudadanos y los canales de información juega un rol fundamental. Clásicamente los medios de comunicación de masas (televisión, radio y prensa escrita) han sido entendidos como los encargados de proveer la información necesaria para el ejercicio de una ciudadanía informada. Sin embargo, en el contexto chileno actual, la legitimidad de estos medios tradicionales también se encuentra fuertemente cuestionada, siendo percibidos por amplios sectores como actores sesgados, concentrados o distantes de las realidades cotidianas de la población.</p>
<p>La masificación de los medios de comunicación dió paso a una sociedad más globalizada e interconectada partiendo desde la imprenta, periódicos, radios, televisión hasta llegar hoy en día a una era de redes sociales. Estos distintos medios desempeñan un rol clave en la representación de la realidad y por lo tanto en la comprensión que las personas tienen de la misma <span class="citation" data-cites="friderichsen2022">(<a href="#ref-friderichsen2022" role="doc-biblioref">Friderichsen et al. 2022</a>)</span></p>
<p>Gracias a muchos estudios sabemos que “el uso de las redes sociales está estrechamente vinculado a la participación política” <span class="citation" data-cites="scherman2021">(<a href="#ref-scherman2021" role="doc-biblioref">Scherman and Rivera 2021</a>)</span>, y esto se ha evidenciado en el último tiempo. Como explican los autores del artículo titulado “Funcionamiento discursivo de la extrema derecha chilena en prensa y TikTok: revisionismo histórico a 50 años del golpe de Estado”, tras la conmemoración de los 50 años del Golpe de Estado efectuado en Chile por fuerzas militares y políticas en el año 1973 existieron muchos debates en la esfera pública chilena y “uno de los espacios privilegiados de estos debates estuvo en las plataformas de redes sociales” <span class="citation" data-cites="riveralópez2024">(<a href="#ref-riveralópez2024" role="doc-biblioref">Rivera López et al. 2024</a>)</span></p>
<p>Tras lo planteado, nos hacemos la siguiente pregunta de investigación: ¿Cómo afecta la frecuencia del uso de medios de comunicación para informarse de política al nivel de autoritarismo en las personas de Chile?&nbsp;</p>
<p>​Asimismo, entendemos que la sociedad chilena no experimenta el uso de medios de comunicación de manera homogénea. Siguiendo las directrices de la sociología de las cohortes y la estratificación, incorporamos como variables de control las cohortes generacionales (edad), el nivel educativo de las y los encuestados, y el sexo (hombre/mujer) Esto nos permite sostener como hipótesis que el impacto de la prensa sobre el nivel de autoritarismo en las personas estará fuertemente mediado por el sexo, el perfil crítico de las generaciones más jóvenes, quienes crecieron en un entorno mediático digitalizado y post-estallido, y por los sectores con mayor capital cultural y educativo, quienes poseen herramientas de análisis crítico más agudas respecto al rol del poder político y mediático en el país.</p>
<p>​Para responder empíricamente a esta problemática, este reporte dinámico utiliza los datos de la Encuesta Longitudinal Social de Chile (ELSOC 2022), herramientas que nos permitirán operacionalizar una escala compleja de autoritarismo de derechas, evaluar su consistencia interna y analizar su grado de asociación con nuestras variables independientes.</p>
<p>Finalmente, este trabajo pretende sistematizar dichos hallazgos en un formato de reporte dinámico mediante Quarto, facilitando la visualización de los datos y su consulta pública a través de la plataforma GitHub.</p>
</section>
<section id="base-de-datos." class="level2">
<h2 class="anchored" data-anchor-id="base-de-datos.">Base de Datos.</h2>
<p>Para realizar este estudio ocuparemos la base de datos “El Estudio Longitudinal Social de Chile (ELSOC)” (<a href="https://conferencias.coes.cl/encuesta-panel/" class="uri">https://conferencias.coes.cl/encuesta-panel/</a>) específicamente la ola 6 correspondiente al año 2022.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#1. Cargamos los paquetes a utilizar.-</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pacman)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">p_load</span>(tidyverse, haven, dplyr, car)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co">#2. Cargamos la base de datos a utilizar.-</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>base_elsoc <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(<span class="st">"C:/Users/belen/OneDrive/Documentos/GitHub/confianza-medios-edad-educacion/Input/ELSOC_Long_2016_2023.dta"</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">#2.1 Elegimos la ola 6, que corresponde a la del 2022.-</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>elsoc2022 <span class="ot">&lt;-</span> base_elsoc <span class="sc">%&gt;%</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ola <span class="sc">==</span> <span class="dv">6</span>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(elsoc2022)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="elección-de-variables." class="level2">
<h2 class="anchored" data-anchor-id="elección-de-variables.">Elección de variables.</h2>
<ul>
<li>Variable “Edad”:</li>
</ul>
<p>El nombre de esta variable en la base de datos es “edad”. Es una variable de nivel de medición de intervalo/razón y registra los años cumplidos de cada persona con un rango que va desde los 19 a los 78 años. Para los fines de esta investigación, funciona como un indicador fundamental de la “cohorte” o grupo generacional al que pertenece el individuo. Su importancia radica en que la edad nos permite identificar el marco de socialización política y mediática bajo el cual se formó cada sujeto.</p>
<ul>
<li>Variable “Sexo”:</li>
</ul>
<p>El nombre de esta variable en la base de datos es “sexo”. Es de caracter nominal y clasifica a los participantes entre hombres y mujeres, funcionando como un factor de contraste fundamental para observar si el género influye en la forma autoritaria de pensar y actuar. En la sociología de la comunicación, el sexo se utiliza a menudo para identificar si existen sesgos de percepción o diferencias en el vínculo con el sistema; de hecho, parte de la literatura internacional sugiere una “predisposición femenina a participar menos, pero a confiar más en las personas e instituciones”. Bajo esta premisa, se podría esperar que las mujeres presenten niveles de autoritarismo más altos hacia que los hombres.</p>
<p>Sin embargo, al aterrizar este análisis al escenario local, la evidencia sugiere un comportamiento distinto. Diversos estudios indican que “en Chile no existe una diferencia significativa entre hombres y mujeres a la hora de confiar en las instituciones”. Esto implica que el descrédito mediático parece ser un fenómeno que atraviesa la identidad de género de manera uniforme. Al respecto, <span class="citation" data-cites="friderichsen2022">(<a href="#ref-friderichsen2022" role="doc-biblioref">Friderichsen et al. 2022</a>)</span> mencionan que este sentimiento de desconfianza se consolidó tras la crisis social de 2019, donde consignas como “Apaga la tele” o “La prensa miente” se hicieron muy populares y advirtieron un cambio en la percepción y valoración de los medios por parte de las personas” de forma transversal.</p>
<p>Por lo tanto, incluir el sexo en esta investigación no solo permite validar si estas tendencias de igualdad se mantienen en los datos más recientes, sino que también sirve como un filtro de control esencial. Su objetivo es asegurar que los hallazgos sobre la edad o el nivel educacional sean sólidos y representativos de la sociedad en su conjunto, confirmando si la crisis de legitimidad de la democracia es, efectivamente, un malestar ciudadano que no distingue entre hombres y mujeres.</p>
<ul>
<li>Variable “Nivel Educacional”:</li>
</ul>
<p>El nombre de esta variable es “niveleduc”. Se trata de una variable de nivel de medición ordinal la cual clasifica a los individuos según su máximo nivel de instrucción alcanzado: 1. sin estudios, 2. educación básica o preparatoria incompleta, 3. educación básica o preparatoria completa, 4. educación media o humanidades incompletas, 5. educación media o humanidades completa, 6. técnico superior incompleto, 7. técnico superior completo, 8. universitaria incompleta, 9. universitaria completa, 10. estudios de posgrado (magíster o doctorado), sin embargo lo dividimos en tres grupos: “Básica”, “Media”, “Superior”. Representa el “capital cultural” o las herramientas cognitivas con las que cuenta cada persona para interpretar la realidad. En este estudio, el nivel educativo se analiza como una herramienta crítica que define la relación entre el ciudadano y el sistema de medios. Según los planteamientos de <span class="citation" data-cites="espinoza-bianchini2023">(<a href="#ref-espinoza-bianchini2023" role="doc-biblioref">Espinoza-Bianchini 2023</a>)</span>, una mayor formación académica tiende a expandir los horizontes de pensamiento de las personas, entregándoles más recursos intelectuales y sociales para generar redes, lo que suele potenciar la confianza hacia los demás (confianza interpersonal).</p>
<p>Para nuestra investigación, esta variable es fundamental porque nos permite observar si en Chile el nivel educativo tiene relación con un mayor o menor nivel de autoritarismo en las personas.</p>
<ul>
<li>Variable “Uso de medios de comunicación masivos para informarse sobre política”:</li>
</ul>
<p>Es una variable de medición ordinal. El fraseo se consulta por la frecuencia con la que el encuestado se informa sobre política a través de televisión, radio, diarios o internet (En el cuestionario es la variable C14_02, pero en la base de datos le pusimos el nombre de info_politica_medios) Es clave para nuestro análisis ya que nos permite entender si un mayor/menor consumo de estos medios para la información sobre política permitirá un mayor o menor rango en la escala de Autoritarismo.</p>
<section id="elección-de-variables-para-la-variable-latente-de-autoritarismo" class="level3">
<h3 class="anchored" data-anchor-id="elección-de-variables-para-la-variable-latente-de-autoritarismo">Elección de variables para la Variable Latente de “Autoritarismo”</h3>
<p>Para la construcción de nuestra variable latente nos basamos en la Escala de Autoritarismo de Derecha desarrollada por el psicólogo Bob Altemeyer. En esta escala, y cito a <span class="citation" data-cites="cárdenas2010">(<a href="#ref-cárdenas2010" role="doc-biblioref">Cárdenas and Parra 2010</a>)</span> en su texto “Adaptación y validación de la Versión Abreviada de la Escala de Autoritarismos de Derechas (RWA) en una muestra chilena” se mide la “covariación de tres grupos de actitudes: sumisión autoritaria, agresión autoritaria y convencionalismo” (Cardenas &amp; Parra, 2010, p.&nbsp;62).</p>
<p>Por medidas prácticas elegimos una variable del cuestionario ELSOC 2022 por cada uno de esos tres grupos de actitudes.</p>
<ul>
<li>Variable “Sumision Autoritaria”</li>
</ul>
<p>Esta actitud se refiere&nbsp; al&nbsp; “grado&nbsp; de&nbsp; sometimiento&nbsp; a&nbsp; las&nbsp; autoridades percibidas&nbsp; como&nbsp; legítimas&nbsp; dentro&nbsp; de&nbsp; la&nbsp; sociedad&nbsp; en&nbsp; que&nbsp; uno&nbsp; vive” (<span class="citation" data-cites="cárdenas2010">(<a href="#ref-cárdenas2010" role="doc-biblioref">Cárdenas and Parra 2010</a>)</span></p>
<p>- C18_05. “Lo que nuestro país necesita es un mandatario/a fuerte con la determinación para llevarnos por el camino correcto”</p>
<ul>
<li>Variable “Agresión Autoritaria”</li>
</ul>
<p>“La agresión autoritaria aludiría a una forma de agresividad general, dirigida contra las personas que se perciben como sancionadas por la autoridad legítima” (<span class="citation" data-cites="cárdenas2010">(<a href="#ref-cárdenas2010" role="doc-biblioref">Cárdenas and Parra 2010</a>)</span></p>
<p>- C37_05. Chile debería tomar medidas más drásticas para impedir el ingreso de inmigrantes al país.&nbsp;</p>
<ul>
<li>Variable “Convencionalismo”</li>
</ul>
<p>“El&nbsp; convencionalismo&nbsp; refiere&nbsp; al&nbsp; grado&nbsp; de&nbsp; adhesión a&nbsp; las&nbsp; normas&nbsp; sociales&nbsp; aprobadas&nbsp; por&nbsp; la&nbsp; sociedad&nbsp; y&nbsp; sus&nbsp; autoridades” (<span class="citation" data-cites="cárdenas2010">(<a href="#ref-cárdenas2010" role="doc-biblioref">Cárdenas and Parra 2010</a>)</span></p>
<p>- R12_06. ¿Qué tan de acuerdo o en desacuerdo está con que los inmigrantes que viven en Chile adopten las costumbres y tradiciones chilenas?&nbsp;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#3. Seleccionamos variables.-</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>elsoc6variables <span class="ot">&lt;-</span> elsoc2022 <span class="sc">%&gt;%</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">sexo =</span> sexo_enc,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">edad   =</span> edad_enc,   </span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">info_politica_medios =</span> c14_02,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">niveleduc =</span> m01,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">sumision_auto =</span> c18_05,</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">agresion_auto =</span> c37_05,</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">convencionalismo =</span> r12_03)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="co">#4. Eliminamos los NAs o casos perdidos.-</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>elsoc6limpia <span class="ot">&lt;-</span> elsoc6variables <span class="sc">%&gt;%</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">edad =</span> <span class="fu">na_if</span>(edad, <span class="sc">-</span><span class="dv">888</span>),</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">edad =</span> <span class="fu">na_if</span>(edad, <span class="sc">-</span><span class="dv">999</span>),</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">info_politica_medios =</span> <span class="fu">na_if</span>(info_politica_medios, <span class="sc">-</span><span class="dv">888</span>),</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">info_politica_medios =</span> <span class="fu">na_if</span>(info_politica_medios, <span class="sc">-</span><span class="dv">999</span>),</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">sumision_auto =</span> <span class="fu">na_if</span>(sumision_auto, <span class="sc">-</span><span class="dv">888</span>),</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">sumision_auto =</span> <span class="fu">na_if</span>(sumision_auto, <span class="sc">-</span><span class="dv">999</span>),</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">niveleduc =</span> <span class="fu">na_if</span>(niveleduc, <span class="sc">-</span><span class="dv">888</span>),</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">niveleduc =</span> <span class="fu">na_if</span>(niveleduc, <span class="sc">-</span><span class="dv">999</span>),</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">agresion_auto =</span> <span class="fu">na_if</span>(agresion_auto, <span class="sc">-</span><span class="dv">888</span>),</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">agresion_auto =</span> <span class="fu">na_if</span>(agresion_auto, <span class="sc">-</span><span class="dv">999</span>),</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">convencionalismo =</span> <span class="fu">na_if</span>(convencionalismo, <span class="sc">-</span><span class="dv">888</span>),</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">convencionalismo =</span> <span class="fu">na_if</span>(convencionalismo, <span class="sc">-</span><span class="dv">999</span>))<span class="sc">%&gt;%</span> </span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(edad,sexo,info_politica_medios,niveleduc,sumision_auto,agresion_auto,convencionalismo)</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(elsoc6limpia)</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a><span class="co">#5. Recodificamos la variable "EDAD" en grupos etarios.-</span></span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>elsoc6limpia <span class="ot">&lt;-</span> elsoc6limpia <span class="sc">%&gt;%</span></span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>    <span class="at">niveleduc =</span> <span class="fu">suppressWarnings</span>(</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>      <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(niveleduc))))</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>elsoc6 <span class="ot">&lt;-</span> elsoc6limpia <span class="sc">%&gt;%</span></span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a>    <span class="at">tramo_edad =</span> <span class="fu">case_when</span>(</span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a>      edad <span class="sc">&gt;=</span> <span class="dv">18</span> <span class="sc">&amp;</span> edad <span class="sc">&lt;=</span> <span class="dv">29</span> <span class="sc">~</span> <span class="st">"Jóvenes"</span>,</span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a>      edad <span class="sc">&gt;=</span> <span class="dv">30</span> <span class="sc">&amp;</span> edad <span class="sc">&lt;=</span> <span class="dv">59</span> <span class="sc">~</span> <span class="st">"Adultos"</span>,</span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a>      edad <span class="sc">&gt;=</span> <span class="dv">60</span> <span class="sc">&amp;</span> edad <span class="sc">&lt;=</span> <span class="dv">78</span> <span class="sc">~</span> <span class="st">"Adultos Mayores"</span>,</span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_character_</span>),</span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a>    <span class="at">tramo_edad =</span> <span class="fu">factor</span>(</span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a>      tramo_edad,</span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(</span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Jóvenes"</span>,</span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Adultos"</span>,</span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Adultos Mayores"</span>)),</span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a>    <span class="at">niveleducacion =</span> <span class="fu">case_when</span>(</span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a>      niveleduc <span class="sc">&gt;=</span> <span class="dv">1</span> <span class="sc">&amp;</span> niveleduc <span class="sc">&lt;=</span> <span class="dv">3</span> <span class="sc">~</span> <span class="st">"Básica"</span>,</span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a>      niveleduc <span class="sc">&gt;=</span> <span class="dv">4</span> <span class="sc">&amp;</span> niveleduc <span class="sc">&lt;=</span> <span class="dv">5</span> <span class="sc">~</span> <span class="st">"Media"</span>,</span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a>      niveleduc <span class="sc">&gt;=</span> <span class="dv">6</span> <span class="sc">&amp;</span> niveleduc <span class="sc">&lt;=</span> <span class="dv">10</span> <span class="sc">~</span> <span class="st">"Superior"</span>,</span>
<span id="cb2-59"><a href="#cb2-59" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_character_</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="tablas." class="level2">
<h2 class="anchored" data-anchor-id="tablas.">Tablas.</h2>
<section id="tabla-de-medidas-de-tendencia-central." class="level4">
<h4 class="anchored" data-anchor-id="tabla-de-medidas-de-tendencia-central.">Tabla de Medidas de Tendencia Central.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#6. Tabla de medidas de Tendencia Central</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">p_load</span>(psych)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>tabla_mtc <span class="ot">&lt;-</span> <span class="fu">describe</span>(elsoc6[, <span class="fu">c</span>(<span class="st">"sumision_auto"</span>, <span class="st">"info_politica_medios"</span>, <span class="st">"agresion_auto"</span>, <span class="st">"convencionalismo"</span>)])</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>tabla_mtc <span class="ot">&lt;-</span> tabla_mtc <span class="sc">%&gt;%</span> </span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(n, mean, sd, median, min, max)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(tabla_mtc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        n mean   sd median min max
sumision_auto        1676 3.99 0.84      4   1   5
info_politica_medios 1676 2.91 1.13      3   1   5
agresion_auto        1676 4.19 0.82      4   1   5
convencionalismo     1676 3.07 1.13      3   1   5</code></pre>
</div>
</div>
<p>Esta tabla de estadísiticos descriptivos asume el comportamiento de las principales variables continuas del estudio para una muestra válida de 1,696 observaciones, donde todas comparten un rango de respuesta que va desde un mínimo de 1 hasta un máximo de 5 puntos. Metodológicamente, destaca que la variable vinculada a rasgos autoritarios de agresión presenta el promedio más alto con 4.19 puntos (desviación estándar = 0.82, mediana = 4), seguida de cerca por la sumisión autoritaria con una media de 4.00 puntos (desviación estándar = 0.84, mediana = 4) y el convencionalismo con 3.79 puntos (desviación estándar = 0.75, mediana = 4), lo que refleja una alta concentración de respuestas en los niveles superiores de estas escalas. Por otro lado, la variable de uso de medios para informarse sobre política registra el promedio más bajo y la mayor dispersión relativa del grupo con 2.91 puntos y una desviación estándar de 1.13 (mediana = 3). Sociológicamente, estos datos iniciales sugieren que, mientras las actitudes y orientaciones normativas de orden tienden a ser homogéneas y elevadas en la muestra, la frecuencia del consumo informativo digital muestra un comportamiento mucho más heterogéneo y distribuido de forma equilibrada en torno al punto medio de la escala.</p>
</section>
<section id="tabla-de-frecuencias." class="level4">
<h4 class="anchored" data-anchor-id="tabla-de-frecuencias.">Tabla de Frecuencias.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#7.2 Tabla de frecuencias.</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Frecuencia para Sexo</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>tabla_sexo <span class="ot">&lt;-</span> elsoc6 <span class="sc">%&gt;%</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(sexo) <span class="sc">%&gt;%</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">porcentaje =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n) <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Frecuencia para Tramo Edad</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>tabla_tramoedad <span class="ot">&lt;-</span> elsoc6 <span class="sc">%&gt;%</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(tramo_edad) <span class="sc">%&gt;%</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">porcentaje =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n) <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Frecuencia para Nivel Educacional</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>tabla_educ <span class="ot">&lt;-</span> elsoc6 <span class="sc">%&gt;%</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(niveleducacion) <span class="sc">%&gt;%</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">porcentaje =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n) <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Ver las tablas</span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(tabla_sexo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  sexo          n porcentaje
  &lt;chr&gt;     &lt;int&gt;      &lt;dbl&gt;
1 Femenino   1295       77.3
2 Masculino   381       22.7</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(tabla_tramoedad)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  tramo_edad          n porcentaje
  &lt;fct&gt;           &lt;int&gt;      &lt;dbl&gt;
1 Jóvenes           119       7.10
2 Adultos          1184      70.6 
3 Adultos Mayores   373      22.3 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(tabla_educ)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  niveleducacion     n porcentaje
  &lt;chr&gt;          &lt;int&gt;      &lt;dbl&gt;
1 Básica           376       22.4
2 Media            746       44.5
3 Superior         554       33.1</code></pre>
</div>
</div>
<p>La tabla de frecuencias para la variable “Tramo de Edad” revela una fuerte concentración de la muestra en el segmento adulto, el cual representa la gran mayoría de los casos analizados con un 70.93% (1,203 observaciones). Por su parte, el grupo de adultos mayores constituye el segundo sector con mayor presencia en los datos, alcanzando un 22.05% (374 observaciones), mientras que el tramo correspondiente a los jóvenes exhibe la menor participación en la muestra con apenas un 7.02% (119 observaciones). Desde el punto de vista metodológico, esta distribución dispar es crucial para el análisis posterior, ya que al evaluar el impacto del consumo informativo digital, se debe considerar que la subrepresentación relativa del bloque juvenil frente a los adultos y adultos mayores podría matizar el alcance generalizado de las conclusiones o exigir un control estadístico riguroso según las cohortes generacionales.</p>
<p>Para la variable sexo revela una marcada asimetría en la composición de la muestra analizada, exhibiendo una fuerte prevalencia del segmento femenino. Metodológicamente, se observa que el grupo de mujeres (Femenino) concentra la gran mayoría de los datos con un 77.30% del total, correspondiente a 1,311 observaciones válidas, mientras que el grupo de hombres (Masculino) alcanza apenas un 22.70%, equivalente a 385 observaciones. Desde un punto de vista analítico, es fundamental reportar este desequilibrio en la caracterización de la muestra, ya que una subrepresentación tan notoria del sexo masculino podría sesgar los resultados descriptivos generales y exige una interpretación cautelosa al momento de evaluar cómo se vincula el género con las actitudes autoritarias y el consumo de información política en el país.&nbsp;</p>
<p>Finalmente, la variable de nivel educacional muestra una muestra bastante equilibrada, aunque con una clara concentración en las categorías de mayor escolaridad. Metodológicamente, se observa que el nivel de educación Media representa el grupo mayoritario con un 44.46% (754 observaciones), seguido por el nivel Superior con un 32.78% (556 observaciones), mientras que las personas con educación Básica constituyen el segmento menor de la muestra con un 22.76% (386 observaciones). Desde una perspectiva sociológica, esta distribución es altamente favorable para los análisis posteriores, ya que al contar con un número robusto de observaciones en cada categoría, el modelo estadístico posee la representatividad necesaria para evaluar con precisión cómo las brechas en el capital cultural y la escolaridad inciden en el consumo de información política y en la configuración de actitudes ciudadanas en el país.&nbsp;</p>
</section>
</section>
<section id="gráficos." class="level2">
<h2 class="anchored" data-anchor-id="gráficos.">Gráficos.</h2>
<section id="gráfico-para-variable-sexo-y-uso-de-medios-de-comunicación-para-informarse-sobre-política." class="level4">
<h4 class="anchored" data-anchor-id="gráfico-para-variable-sexo-y-uso-de-medios-de-comunicación-para-informarse-sobre-política.">Gráfico para variable Sexo y Uso de Medios de Comunicación para informarse sobre política.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">#8. Gráficos.-</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co">#8.1 Gráfico para Sexo</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(elsoc6, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">as.factor</span>(sexo), <span class="at">y =</span> info_politica_medios, <span class="at">fill =</span> <span class="fu">as.factor</span>(sexo))) <span class="sc">+</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">geom =</span> <span class="st">"bar"</span>) <span class="sc">+</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">stat =</span> <span class="st">"summary"</span>, <span class="at">fun =</span> <span class="st">"mean"</span>, <span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(..y.., <span class="dv">2</span>)), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Promedio de Uso de Medios de Comunicacion para informarse sobre política según Sexo"</span>,</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Sexo (1=Hombre, 2=Mujer)"</span>, </span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Promedio de uso"</span>,</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Sexo"</span>) <span class="sc">+</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The dot-dot notation (`..y..`) was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(y)` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Uso-de-las-redes-sociales-para-informarse-sobre-política-y-su-relación-con-una-actitud-autoritaria_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En este gráfico se muestra el promedio de uso de medios de comunicación para informarse sobre política según el sexo de los encuestados, evidenciando una distribución sumamente homogénea entre ambos grupos. Metodológicamente, se observa que las mujeres (Femenino) presentan un promedio de consumo de 2.92 puntos, mientras que los hombres (Masculino) registran un promedio de 2.86 puntos, lo que representa una diferencia marginal de apenas 0.06 puntos a favor del segmento femenino. Desde una perspectiva sociológica, estos datos descriptivos preliminares sugieren que el género no opera como un factor de estratificación relevante o determinante al momento de explicar la frecuencia con la que la ciudadanía se informa de política en el país.</p>
</section>
<section id="gráficos-para-rango-etario-y-uso-de-medios-de-comunicación-para-informarse-sobre-política." class="level4">
<h4 class="anchored" data-anchor-id="gráficos-para-rango-etario-y-uso-de-medios-de-comunicación-para-informarse-sobre-política.">Gráficos para Rango Etario y Uso de Medios de Comunicación para informarse sobre política.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#8.2 Gráfico para Rango Etario</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(elsoc6, <span class="fu">aes</span>(<span class="at">x =</span> tramo_edad, <span class="at">y =</span> info_politica_medios, <span class="at">fill =</span> tramo_edad)) <span class="sc">+</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">geom =</span> <span class="st">"bar"</span>) <span class="sc">+</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">stat =</span> <span class="st">"summary"</span>, <span class="at">fun =</span> <span class="st">"mean"</span>, <span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(..y.., <span class="dv">2</span>)), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Promedio de Uso de Medios de Comunicacion para informarse sobre política por Tramo de Edad"</span>,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Tramos Edad"</span>,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Promedio de uso"</span>) <span class="sc">+</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Set3"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Uso-de-las-redes-sociales-para-informarse-sobre-política-y-su-relación-con-una-actitud-autoritaria_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Este gráfico describe el promedio de uso de medios de comunicación para informarse sobre política según las distintas cohortes generacionales, mostrando variaciones sutiles pero interesantes entre los grupos. Metodológicamente, se observa que el segmento de los jóvenes registra la frecuencia más alta de consumo informativo con un promedio de 3.15 puntos, seguido por los adultos mayores con 2.95 puntos, mientras que el grupo de adultos concentra el promedio más bajo al marcar 2.87 puntos. Desde una lectura sociológica, este hallazgo preliminar es valioso para la investigación, ya que confirma que las generaciones más jóvenes lideran la frecuencia de exposición a la información política, lo cual se alinea con las tesis sobre el impacto de los nuevos entornos digitales en la juventud.&nbsp;</p>
</section>
<section id="gráficos-para-nivel-educacional-y-uso-de-medios-de-comunicación-para-informarse-sobre-política." class="level4">
<h4 class="anchored" data-anchor-id="gráficos-para-nivel-educacional-y-uso-de-medios-de-comunicación-para-informarse-sobre-política.">Gráficos para Nivel Educacional y Uso de Medios de Comunicación para informarse sobre política.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#8.3 Gráfico para Nivel Educacional</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(elsoc6, <span class="fu">aes</span>(<span class="at">x =</span> niveleducacion, <span class="at">y =</span> info_politica_medios, <span class="at">fill =</span> niveleducacion)) <span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">geom =</span> <span class="st">"bar"</span>) <span class="sc">+</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">stat =</span> <span class="st">"summary"</span>, <span class="at">fun =</span> <span class="st">"mean"</span>, <span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(..y.., <span class="dv">2</span>)), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Promedio de uso de Medios de Comunicacion para informarse sobre politica por Nivel Educacional"</span>,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Nivel de Educación"</span>,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Promedio de uso"</span>) <span class="sc">+</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">option =</span> <span class="st">"plasma"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Uso-de-las-redes-sociales-para-informarse-sobre-política-y-su-relación-con-una-actitud-autoritaria_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Por último, en este gráfico se evidencia una relación lineal y ascendente entre las variables, demostrando que a mayor nivel educativo, aumenta la frecuencia de uso de medios para informarse sobre política en Chile. Metodológicamente, se observa que el grupo con educación básica registra el promedio más bajo con 2.5 puntos, seguido por el nivel medio con 2.83, mientras que el sector con educación superior lidera con la frecuencia más alta al alcanzar un promedio de 3.29 puntos. Estos datos sugieren que el nivel educacional (o capital cultural) opera como un factor de estratificación en el consumo informativo, concentrando la exposición a contenidos políticos en los sectores más escolarizados.</p>
</section>
</section>
<section id="creación-variable-latente-autoritarismo" class="level2">
<h2 class="anchored" data-anchor-id="creación-variable-latente-autoritarismo">Creación Variable Latente “Autoritarismo”</h2>
<section id="alfa-de-cronbach-y-correlación-entre-items." class="level3">
<h3 class="anchored" data-anchor-id="alfa-de-cronbach-y-correlación-entre-items.">Alfa de Cronbach y Correlación entre Items.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">#9. Creación de la variable latente</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co">#9.1 </span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>items_autoritarismo <span class="ot">&lt;-</span> elsoc6 <span class="sc">%&gt;%</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(sumision_auto,agresion_auto,convencionalismo,)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co">#9.2 Sacamos la correlación entre los items</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(items_autoritarismo, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 sumision_auto agresion_auto convencionalismo
sumision_auto        1.0000000     0.2656283        0.1230191
agresion_auto        0.2656283     1.0000000        0.2801880
convencionalismo     0.1230191     0.2801880        1.0000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#9.3 Sacamos el Alfa de Cronbach</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>check.keys<span class="ot">=</span><span class="cn">TRUE</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>alfa_resultado <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">alpha</span>(items_autoritarismo)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>alfa_resultado</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Reliability analysis   
Call: psych::alpha(x = items_autoritarismo)

  raw_alpha std.alpha G6(smc) average_r  S/N   ase mean   sd median_r
      0.44      0.46    0.37      0.22 0.86 0.023  3.7 0.65     0.27

    95% confidence boundaries 
         lower alpha upper
Feldt      0.4  0.44  0.49
Duhachek   0.4  0.44  0.49

 Reliability if an item is dropped:
                 raw_alpha std.alpha G6(smc) average_r  S/N alpha se var.r
sumision_auto         0.42      0.44    0.28      0.28 0.78    0.027    NA
agresion_auto         0.21      0.22    0.12      0.12 0.28    0.037    NA
convencionalismo      0.42      0.42    0.27      0.27 0.72    0.028    NA
                 med.r
sumision_auto     0.28
agresion_auto     0.12
convencionalismo  0.27

 Item statistics 
                    n raw.r std.r r.cor r.drop mean   sd
sumision_auto    1676  0.62  0.67  0.36   0.23  4.0 0.84
agresion_auto    1676  0.70  0.74  0.53   0.36  4.2 0.82
convencionalismo 1676  0.75  0.67  0.38   0.25  3.1 1.13

Non missing response frequency for each item
                    1    2    3    4    5 miss
sumision_auto    0.02 0.05 0.10 0.59 0.25    0
agresion_auto    0.01 0.05 0.05 0.51 0.37    0
convencionalismo 0.06 0.34 0.14 0.37 0.08    0</code></pre>
</div>
</div>
<p>Como podemos observar, el resultado de nuestro Alfa de Cronbach es de 0,4439 lo cual se considera un nivel de consistencia interna moderado-bajo en comparación con los estándares tradicionales de escalas psicométricas (mayor a 0.7) Sin embargo, este resultado debe interpretarse considerando que la escala fue construido a partir de solo tres ítems y utilizando variables adaptadas del cuestionario ELSOC. Intentamos construir nuestra escala con distintas variables, y aun asi lo más alto que pudimos alcanzar fue 0,44. Esto puede ser porque el instrumento originalmente no fue diseñado para medir autoritarismo político de manera directa.</p>
<p>A pesar de ello, las correlaciones entre los ítems son positivas y los análisis de confiabilidad muestran que todas las variables contribuyen a la escala general, por lo que este puede ser utilizado como una medida exploratoria de tendencias autoritarias con cierta precaución.</p>
</section>
</section>
<section id="correlación-entre-escala-de-autoritarismo-y-promedio-de-uso-de-medios-de-comunicación-para-informarse-sobre-política." class="level2">
<h2 class="anchored" data-anchor-id="correlación-entre-escala-de-autoritarismo-y-promedio-de-uso-de-medios-de-comunicación-para-informarse-sobre-política.">Correlación entre Escala de Autoritarismo y Promedio de Uso de medios de comunicación para informarse sobre política.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>elsoc6<span class="sc">$</span>indice_autoritarismo <span class="ot">&lt;-</span> <span class="fu">rowMeans</span>(</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  elsoc6[, <span class="fu">c</span>(</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"sumision_auto"</span>,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"agresion_auto"</span>,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"convencionalismo"</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  )],</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">na.rm =</span> <span class="cn">TRUE</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>  elsoc6<span class="sc">$</span>indice_autoritarismo,</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  elsoc6<span class="sc">$</span>info_politica_medios,</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">use =</span> <span class="st">"complete.obs"</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.06668118</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>matriz_final <span class="ot">&lt;-</span> <span class="fu">cor</span>(</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  elsoc6[, <span class="fu">c</span>(</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"indice_autoritarismo"</span>,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"info_politica_medios"</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  )],</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">use =</span> <span class="st">"complete.obs"</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>  elsoc6<span class="sc">$</span>info_politica_medios,</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>  elsoc6<span class="sc">$</span>indice_autoritarismo,</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Información política por medios"</span>,</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Índice de autoritarismo"</span>,</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Relación entre información política y autoritarismo"</span></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(indice_autoritarismo <span class="sc">~</span> info_politica_medios, <span class="at">data =</span> elsoc6),</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="st">"red"</span>,</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">lwd =</span> <span class="dv">2</span></span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Uso-de-las-redes-sociales-para-informarse-sobre-política-y-su-relación-con-una-actitud-autoritaria_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>La correlación entre el índice de autoritarismo y la variable “información política por medios de comunicación” muestra una correlación negativa muy débil (r = -0.067). Esto indica que, a medida que aumenta la frecuencia con la que las personas se informan sobre política a través de medios como televisión, radio, diarios o internet, tiende a disminuir levemente el nivel de autoritarismo.</p>
<p>No obstante, debido a la baja intensidad de la correlación, la relación entre ambas variables es limitada y no permite afirmar una asociación fuerte entre el consumo de información política y las tendencias autoritarias. En este sentido, los resultados sugieren que el uso de medios para informarse políticamente tendría un efecto reducido sobre el autoritarismo en la muestra analizada.</p>

</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-barriaasenjo2022" class="csl-entry" role="listitem">
Barria Asenjo, Nicol Andrea, Rodrigo Aguilera Hunt, José Cabrera-Sánchez, Antonio Letelier Soto, and Nicolás Alberto Pinochet-Mendoza. 2022. <span>“Ascenso de los discursos de extrema derecha en Chile: una aproximación desde la teoría crítica.”</span> <em>Revista Guillermo de Ockham</em> 20 (2). <a href="https://doi.org/10.21500/22563202.5858">https://doi.org/10.21500/22563202.5858</a>.
</div>
<div id="ref-cárdenas2010" class="csl-entry" role="listitem">
Cárdenas, Manuel, and Luis Parra. 2010. <span>“Adaptación y Validación de La Versión Abreviada de La Escala de Autoritarismos de Derechas (RWA) En Una Muestra Chilena.”</span> <em>Revista de Psicología</em> 19 (1): 61. <a href="https://doi.org/10.5354/0719-0581.2010.17098">https://doi.org/10.5354/0719-0581.2010.17098</a>.
</div>
<div id="ref-espinoza-bianchini2023" class="csl-entry" role="listitem">
Espinoza-Bianchini, Gonzalo. 2023. <span>“Informados y confiados: el efecto del consumo de medios de comunicación tradicional y digital sobre la confianza de los chilenos en 2015.”</span> <em>Revista Chilena de Derecho y Ciencia Política</em> 9 (1): 183–211. <a href="https://doi.org/10.7770/rchdcp-V9N1-art1293">https://doi.org/10.7770/rchdcp-V9N1-art1293</a>.
</div>
<div id="ref-friderichsen2022" class="csl-entry" role="listitem">
Friderichsen, Claudia Ramírez, Pablo Matus Lobos, Pontificia Universidad Católica de Chile, and Pontificia Universidad Católica de Chile. 2022. <span>“Marco de desconfianza mediática: Una propuesta para entender el descrédito de los medios de comunicación.”</span> <em>Chasqui, Revista Latinoamericana de Comunicación</em> 1 (150): 247–62. <a href="https://doi.org/10.16921/chasqui.v0i150.4709">https://doi.org/10.16921/chasqui.v0i150.4709</a>.
</div>
<div id="ref-riveralópez2024" class="csl-entry" role="listitem">
Rivera López, Diego, Fabián Riquelme Csori, Matthieu Vernier, Aracelly Balboa, Anaís Berríos, Victoria V. Rivera, Almendra Núñez, and Marco Antonio Vivar. 2024. <span>“Funcionamiento discursivo de la extrema derecha chilena en prensa y TikTok. Revisionismo histórico a 50 años del Golpe de Estado.”</span> <em>Letras (Lima)</em> 95 (141): 304–24. <a href="https://doi.org/10.30920/letras.95.141.18">https://doi.org/10.30920/letras.95.141.18</a>.
</div>
<div id="ref-scherman2021" class="csl-entry" role="listitem">
Scherman, Andrés, and Sebastian Rivera. 2021. <span>“Social Media Use and Pathways to Protest Participation: Evidence From the 2019 Chilean Social Outburst.”</span> <em>Social Media + Society</em> 7 (4): 20563051211059704. <a href="https://doi.org/10.1177/20563051211059704">https://doi.org/10.1177/20563051211059704</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>